x-build: &x-build
  build:
    context: ..
    dockerfile: dev/Dockerfile
    args:
      USERNAME: $USER

x-common: &x-common
  image: chfs
  volumes:
    - ..:/home/$USER/chfs:cached
    - local:/home/$USER/local:cached
  init: true
  networks:
    - chfs_net
  cap_add:
    - SYS_ADMIN
    - SYS_PTRACE
  devices:
    - /dev/fuse
  security_opt:
    - seccomp:unconfined
    - apparmor:unconfined
  privileged: false
  command: >
    bash -c "sudo service ssh restart && sleep infinity"

services:
  c1:
    <<: [*x-build, *x-common]
    hostname: c1
    container_name: chfs-c1
  c2:
    <<: *x-common
    hostname: c2
    container_name: chfs-c2
  c3:
    <<: *x-common
    hostname: c3
    container_name: chfs-c3
  c4:
    <<: *x-common
    hostname: c4
    container_name: chfs-c4

networks:
  chfs_net:

volumes:
  local:
